# Generated by Django 4.2.2 on 2024-01-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('userTelegramId', models.CharField(db_index=True, max_length=64, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(db_index=True, max_length=64, unique=True)),
            ],
        ),
    ]
