# Generated by Django 4.2.2 on 2024-01-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=32, unique=True)),
                ('password', models.CharField(db_index=True, max_length=56, unique=True)),
                ('plainText', models.CharField(max_length=16)),
                ('quota', models.BigIntegerField(default=0)),
                ('download', models.PositiveIntegerField(default=0)),
                ('upload', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
