# Generated by Django 4.2.2 on 2024-01-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=64, unique=True)),
                ('protocol', models.CharField(default='trojan-go', max_length=64)),
                ('sni', models.CharField(default='microsoft.com', max_length=64)),
                ('type', models.CharField(default='ws', max_length=32)),
                ('path', models.CharField(max_length=32)),
                ('shaEncryption', models.CharField(default='aes-128-gcm', max_length=64, null=True)),
                ('encryptionKey', models.CharField(max_length=16, null=True)),
                ('tag', models.TextField()),
                ('sumTraffice', models.IntegerField()),
                ('usedTraffice', models.FloatField(default=0.0)),
                ('ban', models.BooleanField(default=False)),
            ],
        ),
    ]
