# Generated by Django 4.2.2 on 2024-01-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0002_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expireTime',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
