# Generated by Django 4.2.2 on 2024-01-20 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0003_user_expiretime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='expireTime',
        ),
    ]
