# Generated by Django 4.2.2 on 2024-01-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0004_remove_user_expiretime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='download',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='upload',
            field=models.BigIntegerField(default=0),
        ),
    ]
