# Generated by Django 4.2.2 on 2024-01-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0006_node_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='ip',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
