# Generated by Django 4.2.2 on 2024-01-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0007_alter_node_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='entry',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='expireTime',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
