# Generated by Django 4.2.2 on 2024-01-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0008_node_entry_node_expiretime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='ban',
        ),
        migrations.RemoveField(
            model_name='node',
            name='encryptionKey',
        ),
        migrations.RemoveField(
            model_name='node',
            name='expireTime',
        ),
        migrations.RemoveField(
            model_name='node',
            name='path',
        ),
        migrations.RemoveField(
            model_name='node',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='node',
            name='shaEncryption',
        ),
        migrations.RemoveField(
            model_name='node',
            name='sni',
        ),
        migrations.RemoveField(
            model_name='node',
            name='sumTraffice',
        ),
        migrations.RemoveField(
            model_name='node',
            name='type',
        ),
        migrations.RemoveField(
            model_name='node',
            name='usedTraffice',
        ),
        migrations.AlterField(
            model_name='node',
            name='entry',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
