# Generated by Django 4.2.2 on 2024-01-25 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0009_remove_node_ban_remove_node_encryptionkey_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='tag',
        ),
    ]
