# Generated by Django 4.2.2 on 2024-01-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0010_remove_node_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='tag',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
