# Generated by Django 4.2.2 on 2024-01-26 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0011_node_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
