# Generated by Django 4.2.2 on 2024-01-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0012_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='sort',
            field=models.IntegerField(null=True),
        ),
    ]
