# Generated by Django 4.2.4 on 2024-01-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(db_index=True, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32, null=True)),
                ('createTime', models.IntegerField()),
            ],
        ),
    ]
