# Generated by Django 4.2.4 on 2024-01-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
