# Generated by Django 4.2.4 on 2024-01-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_users_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('no', models.CharField(db_index=True, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=32)),
                ('time', models.IntegerField()),
                ('price', models.CharField(max_length=12)),
                ('icon', models.TextField()),
                ('stock', models.IntegerField()),
                ('flow', models.IntegerField()),
            ],
        ),
    ]
