# Generated by Django 4.2.4 on 2024-01-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='type',
            field=models.BooleanField(default=False),
        ),
    ]
