# Generated by Django 4.2.4 on 2024-01-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_plans_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='recommend',
            field=models.CharField(default=1, max_length=24),
            preserve_default=False,
        ),
    ]
