# Generated by Django 4.2.4 on 2024-01-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_plans_recommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='recommend',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
