# Generated by Django 4.2.4 on 2024-01-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_plans_recommend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('no', models.CharField(db_index=True, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('local', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('magnification', models.IntegerField(default=1)),
                ('delay', models.IntegerField(default=100)),
                ('load', models.IntegerField(default=0)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
    ]
