# Generated by Django 4.2.4 on 2024-01-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_servers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='no',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
