# Generated by Django 4.2.4 on 2024-01-15 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_servers_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowRecord',
            fields=[
                ('no', models.CharField(db_index=True, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('date', models.CharField(max_length=24)),
                ('dayDetialFlow', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users')),
            ],
        ),
    ]
