# Generated by Django 4.2.4 on 2024-01-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_flowrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowrecord',
            name='date',
            field=models.IntegerField(),
        ),
    ]
