# Generated by Django 4.2.4 on 2024-01-15 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_flowrecord_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='expire',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.plans'),
            preserve_default=False,
        ),
    ]
