# Generated by Django 4.2.4 on 2024-01-15 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_users_expire_users_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.plans'),
        ),
    ]
