# Generated by Django 4.2.4 on 2024-01-15 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_users_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('no', models.CharField(db_index=True, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('expireTime', models.IntegerField()),
                ('remainingFlow', models.IntegerField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plans')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users')),
            ],
        ),
    ]
