# Generated by Django 4.2.4 on 2024-01-15 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_users_expire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('no', models.CharField(db_index=True, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('createTime', models.IntegerField()),
                ('price', models.CharField(max_length=16)),
                ('key', models.CharField(max_length=8)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plans')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users')),
            ],
        ),
    ]
