# Generated by Django 4.2.4 on 2024-01-15 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Orders',
        ),
    ]
