# Generated by Django 4.2.4 on 2024-01-16 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_orders_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowrecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='user',
        ),
        migrations.DeleteModel(
            name='Servers',
        ),
        migrations.DeleteModel(
            name='FlowRecord',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
