# Generated by Django 4.2.4 on 2024-01-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_delete_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='anonymous',
        ),
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
        migrations.AddField(
            model_name='users',
            name='code',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(db_index=True, default=1, max_length=32, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
