# Generated by Django 4.2.4 on 2024-01-16 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_users_anonymous_remove_users_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('no', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('user', models.CharField(max_length=32, null=True)),
                ('createTime', models.IntegerField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users')),
            ],
        ),
    ]
