# Generated by Django 4.2.4 on 2024-01-16 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Orders',
        ),
    ]
