# Generated by Django 4.2.4 on 2024-01-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_rename_order_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
