# Generated by Django 4.2.4 on 2024-01-16 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_orders_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plans'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.users'),
        ),
    ]
