# Generated by Django 4.2.4 on 2024-01-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_orders_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='actuallyPaid',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
