# Generated by Django 4.2.4 on 2024-01-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_orders_actuallypaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='discount',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
    ]
