# Generated by Django 4.2.4 on 2024-01-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_orders_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('no', models.CharField(db_index=True, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('sumCount', models.IntegerField()),
                ('useCount', models.IntegerField(default=0)),
                ('code', models.CharField(max_length=6)),
                ('expire', models.IntegerField()),
                ('effect', models.CharField(max_length=16)),
            ],
        ),
    ]
