# Generated by Django 4.2.4 on 2024-01-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_discountcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('local', models.CharField(max_length=32)),
                ('magnification', models.IntegerField(default=1)),
                ('delay', models.IntegerField(default=100)),
                ('load', models.IntegerField(default=0)),
                ('ip', models.CharField(max_length=16)),
                ('state', models.BooleanField(default=True)),
                ('disney', models.BooleanField(default=True)),
                ('netflix', models.BooleanField(default=True)),
                ('dazm', models.BooleanField(default=True)),
            ],
        ),
    ]
