# Generated by Django 4.2.4 on 2024-01-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_servers'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='openai',
            field=models.BooleanField(default=True),
        ),
    ]
