# Generated by Django 4.2.4 on 2024-01-18 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_remove_servers_ip'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Member',
        ),
    ]
