# Generated by Django 4.2.4 on 2024-01-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_rename_users_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=56)),
                ('quota', models.BigIntegerField(default=0)),
                ('download', models.PositiveIntegerField(default=0)),
                ('upload', models.PositiveIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['password'], name='main_user_passwor_c910fe_idx')],
            },
        ),
    ]
