# Generated by Django 4.2.4 on 2024-01-18 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_user'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='user',
            new_name='users_passwor_a706a3_idx',
            old_name='main_user_passwor_c910fe_idx',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
