# Generated by Django 4.2.4 on 2024-01-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_user_plaintext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='expireTime',
        ),
        migrations.AddField(
            model_name='user',
            name='expireTime',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
