# Generated by Django 4.2.4 on 2024-01-18 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_remove_member_expiretime_user_expiretime'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='expireTime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.plans'),
        ),
    ]
