# Generated by Django 4.2.4 on 2024-01-18 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_member_expiretime_member_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.member'),
        ),
    ]
