# Generated by Django 4.2.4 on 2024-01-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='bascEmailNotify',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='member',
            name='cloudRules',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='concurrent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='marketingEmailNotify',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='member',
            name='rateLimit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='system',
            field=models.BooleanField(default=True),
        ),
    ]
