# Generated by Django 4.2.4 on 2024-01-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_remove_user_expiretime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('domain', models.CharField(db_index=True, max_length=64, unique=True)),
                ('protocol', models.CharField(default='trojan-go', max_length=64)),
                ('tfo', models.BooleanField(default=True)),
                ('interval', models.IntegerField(default=172800)),
                ('filename', models.CharField(default='ZOOM', max_length=32)),
                ('remove_emoji', models.BooleanField(default=False)),
                ('sni', models.CharField(default='microsoft.com', max_length=64)),
                ('type', models.CharField(default='ws', max_length=32)),
                ('path', models.CharField(max_length=32)),
                ('shaEncryption', models.CharField(default='aes-128-gcm', max_length=64, null=True)),
                ('encryptionKey', models.CharField(max_length=16, null=True)),
            ],
        ),
    ]
