# Generated by Django 4.2.4 on 2024-01-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
