# Generated by Django 4.2.4 on 2024-01-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_alter_node_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='tag',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
