# Generated by Django 4.2.4 on 2024-01-19 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_node_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='node',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='node',
            name='remove_emoji',
        ),
        migrations.RemoveField(
            model_name='node',
            name='tfo',
        ),
    ]
