# Generated by Django 4.2.4 on 2024-01-19 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_remove_node_filename_remove_node_interval_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inviteCode', models.CharField(max_length=6)),
                ('inviteTime', models.IntegerField()),
                ('subscription', models.BooleanField(default=True)),
                ('commission', models.CharField(default='0', max_length=12)),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.member')),
            ],
        ),
    ]
