# Generated by Django 4.2.4 on 2024-01-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_invites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invites',
            name='subscription',
            field=models.BooleanField(default=False),
        ),
    ]
