# Generated by Django 4.2.4 on 2024-01-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_alter_invites_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='balance',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
