# Generated by Django 4.2.4 on 2024-01-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_alter_node_usedtraffice'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='ban',
            field=models.BooleanField(default=False),
        ),
    ]
