# Generated by Django 4.2.4 on 2024-01-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_node_ban'),
    ]

    operations = [
        migrations.AddField(
            model_name='invites',
            name='ce',
            field=models.CharField(default=1, max_length=2, null=True),
        ),
    ]
