# Generated by Django 4.2.4 on 2024-01-20 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_invites_ce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invites',
            name='ce',
        ),
    ]
