# Generated by Django 4.2.4 on 2024-01-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_remove_invites_ce'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='nodeTag',
            field=models.IntegerField(null=True),
        ),
    ]
