# Generated by Django 4.2.4 on 2024-01-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='nextReset',
            field=models.IntegerField(default=0),
        ),
    ]
