# Generated by Django 4.2.4 on 2024-01-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_member_nextreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='nextReset',
            field=models.CharField(default='0', max_length=16),
        ),
    ]
