# Generated by Django 4.2.4 on 2024-01-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_rename_type_plans_giftallowdiscount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plans',
            old_name='giftCurrentCoutn',
            new_name='giftCurrentCount',
        ),
        migrations.AddField(
            model_name='plans',
            name='giftPrice',
            field=models.CharField(default='9999', max_length=12),
        ),
    ]
