# Generated by Django 4.2.4 on 2024-01-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_rename_giftcurrentcoutn_plans_giftcurrentcount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='real',
            field=models.IntegerField(default=1, verbose_name='奸商'),
            preserve_default=False,
        ),
    ]
