# Generated by Django 4.2.4 on 2024-01-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_plans_real'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='real',
            field=models.FloatField(verbose_name='真实倍率'),
        ),
    ]
