# Generated by Django 4.2.4 on 2024-01-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_alter_plans_real'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='type',
            field=models.CharField(default='cycle', max_length=32, null=True),
        ),
    ]
