# Generated by Django 4.2.4 on 2024-01-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_plans_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='expireTime',
            field=models.BigIntegerField(default=0),
        ),
    ]
