# Generated by Django 4.2.4 on 2024-01-31 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_alter_member_expiretime'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryRecord',
            fields=[
                ('code', models.CharField(db_index=True, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('date', models.CharField(max_length=24)),
                ('exchange', models.BooleanField(default=False)),
                ('prize', models.CharField(max_length=32)),
                ('time', models.IntegerField()),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.member')),
            ],
        ),
    ]
