# Generated by Django 4.2.4 on 2024-01-31 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_prizepool'),
    ]

    operations = [
        migrations.AddField(
            model_name='prizepool',
            name='idx',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
