# Generated by Django 4.2.4 on 2024-02-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_prizepool_weights'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('content', models.TextField(null=True)),
                ('tag', models.IntegerField(null=True)),
            ],
        ),
    ]
