# Generated by Django 4.2.4 on 2024-02-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_rename_tag_config_updatetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('createTime', models.IntegerField()),
                ('user', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32)),
                ('state', models.IntegerField(default=0)),
            ],
        ),
    ]
