# Generated by Django 4.2.4 on 2024-02-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_ticketrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='temporaryTraffic',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
