# Generated by Django 4.2.4 on 2024-02-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_remove_plans_featrue'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='account',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plans',
            name='nodes',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='plans',
            name='panel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plans',
            name='record',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plans',
            name='reset',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plans',
            name='systemCount',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plans',
            name='unlock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plans',
            name='welfare',
            field=models.BooleanField(default=True),
        ),
    ]
