# Generated by Django 4.2.4 on 2024-02-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_plans_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
