from django.db import models

class Node(models.Model):
  domain = models.CharField(max_length=64,unique=True,db_index=True)
  ip = models.CharField(max_length=32,unique=True)
  entry = models.CharField(max_length=64,null=True)
  tag = models.TextField()
  sort = models.IntegerField(null=True)
  # protocol = models.CharField(max_length=64,default="trojan-go")
  # sni = models.CharField(max_length=64,default="microsoft.com")
  # type = models.CharField(max_length=32,default="ws")
  # path = models.CharField(max_length=32)
  # shaEncryption = models.CharField(max_length=64,default="aes-128-gcm",null=True)
  # encryptionKey = models.CharField(max_length=16,null=True)
  # tag = models.TextField()
  # sumTraffice = models.IntegerField()
  # usedTraffice = models.FloatField(default=0.0)
  # ban = models.BooleanField(default=False)
  # expireTime = models.IntegerField()
  # entry = models.CharField(max_length=32,null=True)